try { console.log('a'); } catch(err) {}